### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/enumerable#1]
1. convert the whole enum to an array
2. translate enum

**Comment by betterthanclay** [comment]
Hi Viktor. 

There are a couple of array export methods on the interface that should cover #1 - you can map keys to labels or keys to values currently.

When you say "translate", do you mean translating string values of cases? If so, that's a bit out of scope for this library 🙂

**Comment by szepeviktor** [comment]
> When you say "translate", do you mean translating string values of cases?

Yes.

**Comment by betterthanclay** [comment]
Yeah - at least for now, this is outside of the scope of what I was aiming for with this library. Instead it would be better placed in a dedicated translation library that has specific support for enums.. I'll keep it in mind though 👍
